Import('env')

src_testlib = [
  'tcase_eventbus_event.c',
  'tcase_eventbus_bus.c',
  'test_eventbus_helper.c',
]

env.Lib('eventbus-tests', src_testlib)

env.Lib('eventbusdefimpl', [ 'test_eventbus_defimpl.c' ])

libs = [
	'eventbus-tests',
	'eventbusintf', 'eventbus', 'eventbusdefimpl',

  'osmemintf', 'osmem', 'osmemdefimpl',
  'osthreadingintf', 'osthreading', 'osthreadingdefimpl',
  'osutilsintf', 'osutils', 'osutilsdefimpl',
  'listintf', 'list', 'listdefimpl',
]

tests =  env.App('eventbus-tests', 'test_eventbus.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('eventbustests', tests)
