Import('env')

src_intf = [
  'osutilsIntf.c',
]

src_lib = [
  'osutils_random.c',
  'osutils_sleep.c',
  'osutils_time.c',
]

intf = env.Lib('osutilsintf', src_intf)
lib = env.Lib('osutils', src_lib)

env.Alias('osutils', [ intf, lib ])
env.Alias('osa', [ intf, lib ])
