Import('env')

src_testlib = [
	'tcase_osmem.c',
]

env.Lib('osmem-tests', src_testlib)

env.Lib('osmemdefimpl', [ 'test_osmem_defimpl.c' ])

libs = [
	'osmem-tests',
	'osmemintf', 'osmem', 'osmemdefimpl',
]

tests =  env.App('osmem-tests', 'test_osmem.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('osmemtests', tests)
