Import('env')

src_testlib = [
  'tcase_osreactor_channel.c',
  'tcase_osreactor_reactor.c',
  'test_osreactor_helper.c',
]

env.Lib('osreactor-tests', src_testlib)

env.Lib('osreactordefimpl', [ 'test_osreactor_defimpl.c' ])

libs = [
	'osreactor-tests',
	'osreactorintf', 'osreactor', 'osreactordefimpl',

  'osmemintf', 'osmem', 'osmemdefimpl',
  'osnetintf', 'osnet', 'osnetdefimpl',
  'osthreadingintf', 'osthreading', 'osthreadingdefimpl',

  'listintf', 'list', 'listdefimpl',
]

tests =  env.App('osreactor-tests', 'test_osreactor.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('osreactortests', tests)
