Import('env')

src_intf = [
  'osreactorIntf.c',
]

src_lib = [
  'osreactor_channel.c',
  'osreactor_reactor.c',
]

intf = env.Lib('osreactorintf', src_intf)
lib = env.Lib('osreactor', src_lib)

env.Alias('osreactor', [ intf, lib ])
env.Alias('osa', [ intf, lib ])