Import('env')

src_testlib = [
  'tcase_osthreading_condition.c',
  'tcase_osthreading_mutex.c',
  'tcase_osthreading_thread.c',
  'test_osthreading_helper.c',
]

env.Lib('osthreading-tests', src_testlib)

env.Lib('osthreadingdefimpl', [ 'test_osthreading_defimpl.c' ])

libs = [
	'osthreading-tests',
	'osthreadingintf', 'osthreading', 'osthreadingdefimpl',

  'osmemintf', 'osmem', 'osmemdefimpl',
]

tests =  env.App('osthreading-tests', 'test_osthreading.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('osthreadingtests', tests)
