Import('env')

src_testlib = [
  'tcase_osnet_socket_can.c',
  'tcase_osnet_socket_interface.c',
  'tcase_osnet_socket_tcp.c',
  'tcase_osnet_socket_udp.c',
  'tcase_osnet_socket.c',
  'test_osnet_helper.c',
]

env.Lib('osnet-tests', src_testlib)

env.Lib('osnetdefimpl', [ 'test_osnet_defimpl.c' ])

libs = [
	'osnet-tests',
	'osnetintf', 'osnet', 'osnetdefimpl',

  'osmemintf', 'osmem', 'osmemdefimpl',
]

tests =  env.App('osnet-tests', 'test_osnet.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('osnettests', tests)
