Import('env')

src_testlib = [
  'tcase_ossignal.c',
  'test_ossignal_helper.c',
]

env.Lib('ossignal-tests', src_testlib)

env.Lib('ossignaldefimpl', [ 'test_ossignal_defimpl.c' ])

libs = [
	'ossignal-tests',
	'ossignalintf', 'ossignal', 'ossignaldefimpl',

  'osmemintf', 'osmem', 'osmemdefimpl',
]

tests =  env.App('ossignal-tests', 'test_ossignal.c', LIBS=[ libs ])

env.Alias('unittests', tests)
env.Alias('ossignaltests', tests)
